### Add item sample
POST http://localhost:5000/product
Content-Type: application/json

{
    "product": {
        "id": "item1",
        "name": "Magic item 2",
        "price": 299
    }
}

### Get item sample
GET http://localhost:5000/product/item1
Content-Type: application/json

### Add item sample
POST http://13.93.31.100:5000/product
Content-Type: application/json

{
    "product": {
        "id": "item1",
        "name": "Magic item 2",
        "price": 299
    }
}

### Get item sample
GET http://13.93.31.100:5000/product/item1
Content-Type: application/json

